defaults: &defaults
  adapter: mysql2
  username: root
  password: root
  host: localhost

development:
  <<: *defaults
  database: marlin_dev

test:
  <<: *defaults
  database: marlin_test

production:
  <<: *defaults
  database: marlin_prod