# Amazon Web Services credentials
aws:
  account_id: 0052-0731-7122
  access_key_id: AKIAIDHYYYVTBDWN436Q
  secret_access_key: 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
  keypair_name: Marlin
  availability_zone: eu-west-1c

setup:
  ec2 basics monit ruby unicorn postgresql webapp update

# Global script params
ec2:
  image_id: ami-fb665f8f
  instance_type: t1.micro
  ssh_user: ubuntu

shell:
  extra_options: -L 5433:localhost:5432

webapp:
  name: marlinshop
  github_user: KELiON
  github_repo: KELiON/pinky-marlin

# Nodes and their script params
nodes:
  main:
    ec2:
      elastic_ip: 176.34.107.80
